version: '3.9'

services:
  keyvault-emulator:
    image: azure-keyvault-emulator:latest
    build:
      context: .
    hostname: azure-keyvault-emulator.vault.azure.net
    ports:
      - 5551:5551
      - 5550:5550
    volumes:
      - $PWD/local-certs:/https
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5551
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/azure-keyvault-emulator.key
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/azure-keyvault-emulator.crt
