name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Create Certificate
        run: |
          dotnet dev-certs https --clean
          dotnet dev-certs https --trust
          dotnet dev-certs https -ep ./local-certs/azure-key-vault-emulator.crt -np --format pem
          sudo cp ./local-certs/azure-key-vault-emulator.crt /usr/local/share/ca-certificates/azure-key-vault-emulator.crt
          sudo update-ca-certificates

      - name: Verify
        run: make verify
