name: Verify

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Trust Certificate
        run: |
          sudo cp -r ./local-certs/. /usr/local/share/ca-certificates/.
          sudo update-ca-certificates

      - name: Verify
        run: make verify

      - name: Version and Tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''

      - name: Login to Github Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Image
        run: |
          docker image tag azure-key-vault-emulator ghcr.io/basis-theory/azure-key-vault-emulator:latest
          docker image tag azure-key-vault-emulator ghcr.io/basis-theory/azure-key-vault-emulator:${{ steps.bump_version.outputs.new_tag }}
          docker push ghcr.io/basis-theory/azure-key-vault-emulator:latest
          docker push ghcr.io/basis-theory/azure-key-vault-emulator:${{ steps.bump_version.outputs.new_tag }}
