name: Verify

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Verify
        run: make verify

      - name: Slack Release Alert
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          channel: ${{ secrets.SLACK_RELEASE_CHANNEL_ID }}
          fields: 'repo,commit,message,workflow,job'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  release:
    runs-on: ubuntu-latest
    needs:
      - verify

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Release
        id: release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Publish docker image
        uses: docker/build-push-action@v2
        if: ${{ !(steps.release.outputs.version == null || steps.release.outputs.version == '') }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            basistheory/azure-keyvault-emulator:latest
            basistheory/azure-keyvault-emulator:${{ steps.release.outputs.version }}

      - name: Slack Release Alert
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          channel: ${{ secrets.SLACK_RELEASE_CHANNEL_ID }}
          fields: 'repo,commit,message,workflow,job'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
